project:
  type: website
  preview:
    port: 3000
    browser: false

website:
  title: "GRETL"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - getting_started.qmd
      - documentation.qmd
      - text: "Help"
        menu:
          - text: "Report an Issue"
            icon: bug
            href: https://github.com/sogis/gretl/issues
          - text: "Discussions"
            icon: chat-right-text
            href: https://fubar.ch/
          - text: "FAQ"
            icon: question-circle
            href: getting_started.ipynb#faq
    right:
      - icon: github
        href: https://github.com/sogis/gretl
        aria-label: GitHub
  sidebar:
    style: floating
    contents: auto
  page-footer: 
    left: "Copyright 2023, Amt f√ºr Geoinformation Kanton Solothurn" 
    right: 
      - icon: github
        href: https://github.com/sogis
      - icon: twitter 
        href: https://twitter.com/_sogis 

format:
  html:
    theme: cosmo
    css: styles.css
    header-includes: |
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
    mainfont: Inter
    toc: true
    toc-depth: 4
    grid:
      sidebar-width: 200px
      margin-width: 200px
      body-width: 1000px

